import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "zh-CN" | "zh-TW" | "en";

export const LANGUAGE_NAMES: Record<Language, string> = {
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
  "en": "English",
};

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
}

export const useLanguage = create<LanguageState>()(
  persist(
    (set) => ({
      language: "zh-TW",
      setLanguage: (language: Language) => set({ language }),
    }),
    { name: "language-storage" }
  )
);

// Translation type
type TranslationValue = string | Record<string, string | Record<string, string>>;
type Translations = Record<string, TranslationValue>;

// Simple translation hook
export function useTranslation() {
  const language = useLanguage((state) => state.language);
  
  const t = (key: string, params?: Record<string, string | number>): string => {
    const keys = key.split(".");
    let value: TranslationValue | undefined = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === "object" && k in value) {
        value = (value as Record<string, TranslationValue>)[k];
      } else {
        // Fallback to zh-CN
        value = translations["zh-CN"];
        for (const fallbackKey of keys) {
          if (value && typeof value === "object" && fallbackKey in value) {
            value = (value as Record<string, TranslationValue>)[fallbackKey];
          } else {
            return key; // Return key if not found
          }
        }
        break;
      }
    }
    
    if (typeof value !== "string") return key;
    
    // Replace params
    if (params) {
      let result = value;
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        result = result.replace(new RegExp(`\\{${paramKey}\\}`, "g"), String(paramValue));
      });
      return result;
    }
    
    return value;
  };
  
  return { t, language };
}

// Translations
const translations: Record<Language, Translations> = {
  "zh-CN": {
    common: {
      login: "登录",
      logout: "退出登录",
      save: "保存",
      cancel: "取消",
      confirm: "确认",
      back: "返回",
      next: "下一步",
      loading: "加载中...",
      selectRole: "登录",
      testAccount: "测试账户登录",
      userRole: "普通用户角色",
      adminRole: "管理员角色",
      testUser: "测试用户",
      admin: "管理员",
      goToConsole: "进入控制台",
    },
    home: {
      title: "发现你的职业锚",
      subtitle: "8维度动态测评，精准定位你的核心职业价值观",
      startAssessment: "开始测评",
      viewHistory: "查看历史",
      features: {
        adaptive: "AI 自适应题目",
        adaptiveDesc: "根据你的回答动态调整后续问题",
        scientific: "科学理论基础",
        scientificDesc: "基于施恩职业锚理论",
        personalized: "个性化报告",
        personalizedDesc: "深度分析你的职业倾向",
      },
      stats: {
        users: "用户测评",
        accuracy: "准确率",
        minutes: "平均用时",
      },
    },
    assessment: {
      title: "职业锚测评",
      intro: "接下来你将回答一系列问题，系统会根据你的回答动态调整后续问题。",
      instruction: "请选择真实倾向，而非社会期待或「正确答案」。",
      questionCount: "大约 18-28 道题目",
      estimatedTime: "预计 5-8 分钟完成",
      autoSave: "进度自动保存",
      startButton: "开始答题",
      question: "问题",
      of: "/",
      progress: "进度",
      saveExit: "保存并退出",
      synced: "已同步",
      syncing: "保存中",
      syncFailed: "同步失败",
      autoNext: "选择后自动进入下一题",
      progressSaved: "进度已自动保存",
      previous: "上一题",
      clickToNext: "点击选项自动进入下一题",
      resumeTitle: "检测到未完成的测评",
      resumeDesc: "您有一个未完成的测评（已回答 {count} 题）。是否继续上次的进度？",
      resumeButton: "继续上次",
      restartButton: "重新开始",
      checkingProgress: "检查测评进度...",
      aiSelecting: "AI 正在选择下一题...",
      questionTypes: {
        likert: "态度量表",
        choice: "强制选择",
        scenario: "情境判断",
      },
      dimensions: {
        TF: "技术/专业能力型",
        GM: "管理型",
        AU: "自主/独立型",
        SE: "安全/稳定型",
        EC: "创业/创造型",
        SV: "服务/奉献型",
        CH: "挑战型",
        LS: "生活方式整合型",
      },
      sidebar: {
        title: "实时维度分析",
        subtitle: "8大职业锚维度",
        description: "你的回答正在实时分析中。完成所有问题后，系统将生成完整的职业锚雷达图和详细报告。",
        current: "当前",
        loginPrompt: "登录后可自动保存测评进度，支持跨设备继续测评。",
        careerStage: "当前职业阶段",
      },
      options: {
        stronglyDisagree: "非常不同意",
        disagree: "不同意",
        neutral: "中立",
        agree: "同意",
        stronglyAgree: "非常同意",
      },
    },
    results: {
      title: "测评结果",
      mainAnchor: "高敏感锚",
      conflictAnchors: "冲突锚",
      riskIndex: "风险指数",
      stability: "稳定性",
      mature: "成熟",
      developing: "发展中",
      unclear: "不明确",
      share: "分享结果",
      deepDive: "深度解读",
      actionPlan: "行动计划",
    },
    careerStage: {
      title: "测评选择",
      subtitle: "选择您要进行的测评项目",
      entry: "职场新人",
      entryDesc: "初入职场，探索方向",
      mid: "职场中期",
      midDesc: "有一定经验，寻求突破",
      senior: "资深职场人士",
      seniorDesc: "丰富经验",
      hr: "HR/组织发展",
      hrDesc: "人力资源从业者",
    },
    admin: {
      dashboard: "仪表盘",
      questions: "题库管理",
      analytics: "数据分析",
      users: "用户管理",
      settings: "系统设置",
      totalUsers: "总用户数",
      weeklyNew: "本周新增",
      avgTime: "平均用时",
      questionCount: "题目数量",
      anchorDistribution: "锚点分布",
      recentActivity: "实时动态",
      // Users page
      usersTitle: "用户管理",
      usersDesc: "查看和管理测评用户数据",
      exportUsers: "导出用户数据",
      addUser: "新增用户",
      batchImport: "批量导入",
      searchUser: "搜索用户名或邮箱...",
      allStages: "全部",
      activeUsers: "活跃用户",
      pendingAssessment: "待完成测评",
      avgAssessments: "平均测评次数",
      user: "用户",
      careerStage: "职业阶段",
      mainAnchor: "高敏感锚",
      assessmentCount: "测评次数",
      status: "状态",
      lastActive: "最后活跃",
      actions: "操作",
      active: "活跃",
      pending: "待完成",
      inactive: "不活跃",
      showing: "显示",
      of: "共",
      items: "条",
      prevPage: "上一页",
      nextPage: "下一页",
      viewDetails: "查看详情",
      sendEmail: "发送邮件",
      moreActions: "更多操作",
      deleteUser: "删除用户",
      deleteConfirm: "确定要删除用户",
      deleteSuccess: "用户删除成功",
      addUserTitle: "新增用户",
      editUserTitle: "编辑用户",
      userName: "用户名",
      email: "邮箱",
      importTitle: "批量导入用户",
      importDesc: "请上传CSV或Excel文件，文件需包含：姓名、邮箱、职业阶段",
      downloadTemplate: "下载模板",
      dragOrClick: "拖拽文件到此处，或点击选择文件",
      supportFormat: "支持 .csv, .xlsx 格式",
      importSuccess: "成功导入 {count} 位用户",
      importing: "导入中...",
      // Questions page
      questionsTitle: "题库管理",
      questionsDesc: "管理测评题目，支持新增、编辑、启用/禁用",
      addQuestion: "新增题目",
      batchImportQuestions: "批量导入",
      searchQuestion: "搜索题目内容...",
      totalQuestions: "总题目数",
      enabledQuestions: "已启用",
      draftQuestions: "草稿",
      avgAnswerTime: "平均作答时间",
      question: "题目",
      type: "类型",
      dimension: "维度",
      responseCount: "答题次数",
      enabled: "已启用",
      draft: "草稿",
      preview: "预览",
      edit: "编辑",
      duplicate: "复制",
      delete: "删除",
      deleteQuestionConfirm: "确定要删除此题目？",
      deleteQuestionSuccess: "题目删除成功",
      addQuestionTitle: "新增题目",
      editQuestionTitle: "编辑题目",
      questionText: "题目内容",
      questionType: "题目类型",
      questionDimension: "所属维度",
      options: "选项",
      addOption: "添加选项",
      importQuestionsTitle: "批量导入题目",
      importQuestionsDesc: "请上传CSV或Excel文件，文件需包含：题目内容、类型、维度、选项",
      importQuestionsSuccess: "成功导入 {count} 道题目",
      typeLikert: "量表题",
      typeForcedChoice: "二选一",
      typeScenario: "场景题",
      more: "更多",
      // Career stages
      stageEntry: "职场新人",
      stageMid: "职场中期",
      stageSenior: "高管/创业者",
      stageHR: "HR/组织发展",
      // Analytics page
      analyticsTitle: "数据分析",
      analyticsDesc: "测评数据统计与趋势分析",
      exportReport: "导出报告",
      today: "今日",
      thisWeek: "本周",
      thisMonth: "本月",
      thisQuarter: "本季度",
      thisYear: "本年",
      assessmentTrend: "测评趋势",
      dailyStats: "每日测评人数统计",
      startedAssessment: "开始测评",
      completedAssessment: "完成测评",
      anchorTrendChange: "职业锚趋势变化",
      comparedToPrevious: "与上期对比",
      careerStageDistribution: "职业阶段分布",
      userComposition: "用户群体构成",
      totalAssessments: "总测评人数",
      completionRate: "完成率",
      monday: "周一",
      tuesday: "周二",
      wednesday: "周三",
      thursday: "周四",
      friday: "周五",
      saturday: "周六",
      sunday: "周日",
      // Settings page
      settingsTitle: "系统设置",
      settingsDesc: "配置系统参数与全局选项",
      saveSettings: "保存设置",
      settingsSaved: "设置已保存",
      generalSettings: "基本设置",
      generalSettingsDesc: "系统名称与基础配置",
      systemName: "系统名称",
      minQuestions: "最少题目数",
      maxQuestions: "最多题目数",
      sessionSettings: "会话设置",
      sessionSettingsDesc: "测评会话与超时配置",
      sessionTimeout: "会话超时时间（分钟）",
      sessionTimeoutDesc: "用户在测评过程中无操作超过此时间后，系统将自动保存进度",
      notificationSettings: "通知设置",
      notificationSettingsDesc: "邮件与系统通知配置",
      emailNotifications: "邮件通知",
      emailNotificationsDesc: "用户完成测评后发送结果邮件",
      weeklyReport: "周报汇总",
      weeklyReportDesc: "每周发送系统数据汇总报告",
      maintenanceMode: "维护模式",
      maintenanceModeDesc: "系统维护与紧急操作",
      enableMaintenance: "启用维护模式",
      enableMaintenanceDesc: "开启后用户将无法访问测评系统",
      databaseInfo: "数据库信息",
      databaseInfoDesc: "存储与数据状态",
      userRecords: "用户记录",
      assessmentRecords: "测评记录",
      totalQuestionsCount: "题目总数",
    },
    profile: {
      title: "个人中心",
      assessmentHistory: "测评历史",
      noHistory: "暂无测评记录",
      startFirst: "开始你的第一次测评",
    },
    history: {
      title: "测评历史",
      empty: "还没有测评记录",
      emptyDesc: "完成测评后，你的结果将保存在这里",
      testAccountNote: "测试账户的历史记录",
      testAccountDesc: "测试账户数据仅供演示，不会保存到云端",
    },
  },
  "zh-TW": {
    common: {
      login: "登入",
      logout: "登出",
      save: "儲存",
      cancel: "取消",
      confirm: "確認",
      back: "返回",
      next: "下一步",
      loading: "載入中...",
      selectRole: "登入",
      testAccount: "測試帳戶登入",
      userRole: "一般使用者角色",
      adminRole: "管理員角色",
      testUser: "測試使用者",
      admin: "管理員",
      goToConsole: "進入控制台",
    },
    home: {
      title: "發現你的職業錨",
      subtitle: "8維度動態測評，精準定位你的核心職業價值觀",
      startAssessment: "開始測評",
      viewHistory: "查看歷史",
      features: {
        adaptive: "AI 自適應題目",
        adaptiveDesc: "根據你的回答動態調整後續問題",
        scientific: "科學理論基礎",
        scientificDesc: "基於施恩職業錨理論",
        personalized: "個性化報告",
        personalizedDesc: "深度分析你的職業傾向",
      },
      stats: {
        users: "使用者測評",
        accuracy: "準確率",
        minutes: "平均用時",
      },
    },
    assessment: {
      title: "職業錨測評",
      intro: "接下來你將回答一系列問題，系統會根據你的回答動態調整後續問題。",
      instruction: "請選擇真實傾向，而非社會期待或「正確答案」。",
      questionCount: "大約 18-28 道題目",
      estimatedTime: "預計 5-8 分鐘完成",
      autoSave: "進度自動儲存",
      startButton: "開始答題",
      question: "問題",
      of: "/",
      progress: "進度",
      saveExit: "儲存並退出",
      synced: "已同步",
      syncing: "儲存中",
      syncFailed: "同步失敗",
      autoNext: "選擇後自動進入下一題",
      progressSaved: "進度已自動儲存",
      previous: "上一題",
      clickToNext: "點擊選項自動進入下一題",
      resumeTitle: "檢測到未完成的測評",
      resumeDesc: "您有一個未完成的測評（已回答 {count} 題）。是否繼續上次的進度？",
      resumeButton: "繼續上次",
      restartButton: "重新開始",
      checkingProgress: "檢查測評進度...",
      aiSelecting: "AI 正在選擇下一題...",
      questionTypes: {
        likert: "態度量表",
        choice: "強制選擇",
        scenario: "情境判斷",
      },
      dimensions: {
        TF: "技術/專業能力型",
        GM: "管理型",
        AU: "自主/獨立型",
        SE: "安全/穩定型",
        EC: "創業/創造型",
        SV: "服務/奉獻型",
        CH: "挑戰型",
        LS: "生活方式整合型",
      },
      sidebar: {
        title: "即時維度分析",
        subtitle: "8大職業錨維度",
        description: "你的回答正在即時分析中。完成所有問題後，系統將生成完整的職業錨雷達圖和詳細報告。",
        current: "當前",
        loginPrompt: "登入後可自動儲存測評進度，支援跨裝置繼續測評。",
        careerStage: "當前職業階段",
      },
      options: {
        stronglyDisagree: "非常不同意",
        disagree: "不同意",
        neutral: "中立",
        agree: "同意",
        stronglyAgree: "非常同意",
      },
    },
    results: {
      title: "測評結果",
      mainAnchor: "高敏感錨",
      conflictAnchors: "衝突錨",
      riskIndex: "風險指數",
      stability: "穩定性",
      mature: "成熟",
      developing: "發展中",
      unclear: "不明確",
      share: "分享結果",
      deepDive: "深度解讀",
      actionPlan: "行動計劃",
    },
    careerStage: {
      title: "測評選擇",
      subtitle: "選擇您要進行的測評專案",
      entry: "職場新人",
      entryDesc: "初入職場，探索方向",
      mid: "職場中期",
      midDesc: "有一定經驗，尋求突破",
      senior: "資深職場人士",
      seniorDesc: "豐富經驗",
      hr: "HR/組織發展",
      hrDesc: "人力資源從業者",
    },
    admin: {
      dashboard: "儀表板",
      questions: "題庫管理",
      analytics: "數據分析",
      users: "使用者管理",
      settings: "系統設定",
      totalUsers: "總使用者數",
      weeklyNew: "本週新增",
      avgTime: "平均用時",
      questionCount: "題目數量",
      anchorDistribution: "錨點分佈",
      recentActivity: "即時動態",
      // Users page
      usersTitle: "使用者管理",
      usersDesc: "檢視和管理測評使用者資料",
      exportUsers: "匯出使用者資料",
      addUser: "新增使用者",
      batchImport: "批次匯入",
      searchUser: "搜尋使用者名稱或信箱...",
      allStages: "全部",
      activeUsers: "活躍使用者",
      pendingAssessment: "待完成測評",
      avgAssessments: "平均測評次數",
      user: "使用者",
      careerStage: "職業階段",
      mainAnchor: "高敏感錨",
      assessmentCount: "測評次數",
      status: "狀態",
      lastActive: "最後活躍",
      actions: "操作",
      active: "活躍",
      pending: "待完成",
      inactive: "不活躍",
      showing: "顯示",
      of: "共",
      items: "條",
      prevPage: "上一頁",
      nextPage: "下一頁",
      viewDetails: "查看詳情",
      sendEmail: "傳送信件",
      moreActions: "更多操作",
      deleteUser: "刪除使用者",
      deleteConfirm: "確定要刪除使用者",
      deleteSuccess: "使用者刪除成功",
      addUserTitle: "新增使用者",
      editUserTitle: "編輯使用者",
      userName: "使用者名稱",
      email: "信箱",
      importTitle: "批次匯入使用者",
      importDesc: "請上傳CSV或Excel檔案，檔案需包含：姓名、信箱、職業階段",
      downloadTemplate: "下載模板",
      dragOrClick: "拖曳文件到此處，或點擊選擇文件",
      supportFormat: "支持 .csv, .xlsx 格式",
      importSuccess: "成功匯入 {count} 位使用者",
      importing: "匯入中...",
      // Questions page
      questionsTitle: "題庫管理",
      questionsDesc: "管理測評題目，支持新增、編輯、啟用/禁用",
      addQuestion: "新增題目",
      batchImportQuestions: "批次匯入",
      searchQuestion: "搜尋題目內容...",
      totalQuestions: "總題目數",
      enabledQuestions: "已啟用",
      draftQuestions: "草稿",
      avgAnswerTime: "平均作答時間",
      question: "題目",
      type: "類型",
      dimension: "維度",
      responseCount: "答題次數",
      enabled: "已啟用",
      draft: "草稿",
      preview: "預覽",
      edit: "編輯",
      duplicate: "複製",
      delete: "刪除",
      deleteQuestionConfirm: "確定要刪除此題目？",
      deleteQuestionSuccess: "題目刪除成功",
      addQuestionTitle: "新增題目",
      editQuestionTitle: "編輯題目",
      questionText: "題目內容",
      questionType: "題目類型",
      questionDimension: "所屬維度",
      options: "選項",
      addOption: "添加選項",
      importQuestionsTitle: "批次匯入題目",
      importQuestionsDesc: "請上傳CSV或Excel檔案，檔案需包含：題目內容、類型、維度、選項",
      importQuestionsSuccess: "成功匯入 {count} 道題目",
      typeLikert: "量表題",
      typeForcedChoice: "二選一",
      typeScenario: "場景題",
      more: "更多",
      // Career stages
      stageEntry: "職場新人",
      stageMid: "職場中期",
      stageSenior: "高管/創業者",
      stageHR: "HR/組織發展",
      // Analytics page
      analyticsTitle: "數據分析",
      analyticsDesc: "測評數據統計與趨勢分析",
      exportReport: "匯出報告",
      today: "今日",
      thisWeek: "本週",
      thisMonth: "本月",
      thisQuarter: "本季度",
      thisYear: "本年",
      assessmentTrend: "測評趨勢",
      dailyStats: "每日測評人數統計",
      startedAssessment: "開始測評",
      completedAssessment: "完成測評",
      anchorTrendChange: "職業錨趨勢變化",
      comparedToPrevious: "與上期對比",
      careerStageDistribution: "職業階段分佈",
      userComposition: "使用者群體構成",
      totalAssessments: "總測評人數",
      completionRate: "完成率",
      monday: "週一",
      tuesday: "週二",
      wednesday: "週三",
      thursday: "週四",
      friday: "週五",
      saturday: "週六",
      sunday: "週日",
      // Settings page
      settingsTitle: "系統設定",
      settingsDesc: "配置系統參數與全局選項",
      saveSettings: "儲存設定",
      settingsSaved: "設定已儲存",
      generalSettings: "基本設定",
      generalSettingsDesc: "系統名稱與基礎配置",
      systemName: "系統名稱",
      minQuestions: "最少題目數",
      maxQuestions: "最多題目數",
      sessionSettings: "會話設定",
      sessionSettingsDesc: "測評會話與超時配置",
      sessionTimeout: "會話超時時間（分鐘）",
      sessionTimeoutDesc: "使用者在測評過程中無操作超過此時間後，系統將自動儲存進度",
      notificationSettings: "通知設定",
      notificationSettingsDesc: "信件與系統通知配置",
      emailNotifications: "信件通知",
      emailNotificationsDesc: "使用者完成測評後傳送結果信件",
      weeklyReport: "週報彙總",
      weeklyReportDesc: "每週發送系統數據彙總報告",
      maintenanceMode: "維護模式",
      maintenanceModeDesc: "系統維護與緊急操作",
      enableMaintenance: "啟用維護模式",
      enableMaintenanceDesc: "開啟後使用者將無法存取測評系統",
      databaseInfo: "資料庫資訊",
      databaseInfoDesc: "儲存與資料狀態",
      userRecords: "使用者記錄",
      assessmentRecords: "測評記錄",
      totalQuestionsCount: "題目總數",
    },
    profile: {
      title: "個人中心",
      assessmentHistory: "測評歷史",
      noHistory: "暫無測評記錄",
      startFirst: "開始你的第一次測評",
    },
    history: {
      title: "測評歷史",
      empty: "還沒有測評記錄",
      emptyDesc: "完成測評後，你的結果將儲存在這裡",
      testAccountNote: "測試帳戶的歷史記錄",
      testAccountDesc: "測試帳戶數據僅供演示，不會儲存到雲端",
    },
  },
  "en": {
    common: {
      login: "Login",
      logout: "Logout",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      back: "Back",
      next: "Next",
      loading: "Loading...",
      selectRole: "Login",
      testAccount: "Test Account Login",
      userRole: "User Role",
      adminRole: "Admin Role",
      testUser: "Test User",
      admin: "Admin",
      goToConsole: "Go to Console",
    },
    home: {
      title: "Discover Your Career Anchor",
      subtitle: "8-Dimension Dynamic Assessment for Your Core Career Values",
      startAssessment: "Start Assessment",
      viewHistory: "View History",
      features: {
        adaptive: "AI Adaptive Questions",
        adaptiveDesc: "Questions adapt based on your responses",
        scientific: "Scientific Foundation",
        scientificDesc: "Based on Schein's Career Anchor Theory",
        personalized: "Personalized Reports",
        personalizedDesc: "In-depth analysis of your career orientation",
      },
      stats: {
        users: "Assessments",
        accuracy: "Accuracy",
        minutes: "Avg. Time",
      },
    },
    assessment: {
      title: "Career Anchor Assessment",
      intro: "You will answer a series of questions. The system will dynamically adjust subsequent questions based on your responses.",
      instruction: "Please choose your true preference, not social expectations or 'correct answers'.",
      questionCount: "Approximately 18-28 questions",
      estimatedTime: "Estimated 5-8 minutes",
      autoSave: "Progress auto-saved",
      startButton: "Start Assessment",
      question: "Question",
      of: "/",
      progress: "Progress",
      saveExit: "Save & Exit",
      synced: "Synced",
      syncing: "Saving",
      syncFailed: "Sync Failed",
      autoNext: "Auto-advance after selection",
      progressSaved: "Progress auto-saved",
      previous: "Previous",
      clickToNext: "Click option to auto-advance",
      resumeTitle: "Unfinished Assessment Detected",
      resumeDesc: "You have an unfinished assessment ({count} questions answered). Would you like to continue?",
      resumeButton: "Continue",
      restartButton: "Start Over",
      checkingProgress: "Checking progress...",
      aiSelecting: "AI selecting next question...",
      questionTypes: {
        likert: "Attitude Scale",
        choice: "Forced Choice",
        scenario: "Situational Judgment",
      },
      dimensions: {
        TF: "Technical/Functional",
        GM: "General Management",
        AU: "Autonomy/Independence",
        SE: "Security/Stability",
        EC: "Entrepreneurial Creativity",
        SV: "Service/Dedication",
        CH: "Pure Challenge",
        LS: "Lifestyle Integration",
      },
      sidebar: {
        title: "Real-time Dimension Analysis",
        subtitle: "8 Career Anchor Dimensions",
        description: "Your responses are being analyzed in real-time. After completing all questions, the system will generate a comprehensive radar chart and detailed report.",
        current: "Current",
        loginPrompt: "Login to auto-save progress and continue across devices.",
        careerStage: "Current Career Stage",
      },
      options: {
        stronglyDisagree: "Strongly Disagree",
        disagree: "Disagree",
        neutral: "Neutral",
        agree: "Agree",
        stronglyAgree: "Strongly Agree",
      },
    },
    results: {
      title: "Assessment Results",
      mainAnchor: "High-Sensitivity Anchor",
      conflictAnchors: "Conflicting Anchors",
      riskIndex: "Risk Index",
      stability: "Stability",
      mature: "Mature",
      developing: "Developing",
      unclear: "Unclear",
      share: "Share Results",
      deepDive: "Deep Dive",
      actionPlan: "Action Plan",
    },
    careerStage: {
      title: "Assessment Selection",
      subtitle: "Choose the assessments you want to take",
      entry: "Early Career",
      entryDesc: "New to career, exploring directions",
      mid: "Mid-Career",
      midDesc: "Experienced, seeking breakthrough",
      senior: "Senior Professional",
      seniorDesc: "Extensive experience",
      hr: "HR/OD Professional",
      hrDesc: "Human resources practitioner",
    },
    admin: {
      dashboard: "Dashboard",
      questions: "Question Bank",
      analytics: "Analytics",
      users: "User Management",
      settings: "Settings",
      totalUsers: "Total Users",
      weeklyNew: "Weekly New",
      avgTime: "Avg. Time",
      questionCount: "Questions",
      anchorDistribution: "Anchor Distribution",
      recentActivity: "Recent Activity",
      // Users page
      usersTitle: "User Management",
      usersDesc: "View and manage assessment user data",
      exportUsers: "Export Users",
      addUser: "Add User",
      batchImport: "Batch Import",
      searchUser: "Search name or email...",
      allStages: "All",
      activeUsers: "Active Users",
      pendingAssessment: "Pending Assessment",
      avgAssessments: "Avg. Assessments",
      user: "User",
      careerStage: "Career Stage",
      mainAnchor: "High-Sens Anchor",
      assessmentCount: "Assessments",
      status: "Status",
      lastActive: "Last Active",
      actions: "Actions",
      active: "Active",
      pending: "Pending",
      inactive: "Inactive",
      showing: "Showing",
      of: "of",
      items: "items",
      prevPage: "Previous",
      nextPage: "Next",
      viewDetails: "View Details",
      sendEmail: "Send Email",
      moreActions: "More Actions",
      deleteUser: "Delete User",
      deleteConfirm: "Are you sure you want to delete user",
      deleteSuccess: "User deleted successfully",
      addUserTitle: "Add User",
      editUserTitle: "Edit User",
      userName: "Name",
      email: "Email",
      importTitle: "Batch Import Users",
      importDesc: "Upload a CSV or Excel file containing: Name, Email, Career Stage",
      downloadTemplate: "Download Template",
      dragOrClick: "Drag file here or click to select",
      supportFormat: "Supports .csv, .xlsx formats",
      importSuccess: "Successfully imported {count} users",
      importing: "Importing...",
      // Questions page
      questionsTitle: "Question Bank",
      questionsDesc: "Manage assessment questions, add, edit, enable/disable",
      addQuestion: "Add Question",
      batchImportQuestions: "Batch Import",
      searchQuestion: "Search questions...",
      totalQuestions: "Total Questions",
      enabledQuestions: "Enabled",
      draftQuestions: "Drafts",
      avgAnswerTime: "Avg. Answer Time",
      question: "Question",
      type: "Type",
      dimension: "Dimension",
      responseCount: "Responses",
      enabled: "Enabled",
      draft: "Draft",
      preview: "Preview",
      edit: "Edit",
      duplicate: "Duplicate",
      delete: "Delete",
      deleteQuestionConfirm: "Are you sure you want to delete this question?",
      deleteQuestionSuccess: "Question deleted successfully",
      addQuestionTitle: "Add Question",
      editQuestionTitle: "Edit Question",
      questionText: "Question Text",
      questionType: "Question Type",
      questionDimension: "Dimension",
      options: "Options",
      addOption: "Add Option",
      importQuestionsTitle: "Batch Import Questions",
      importQuestionsDesc: "Upload a CSV or Excel file containing: Question, Type, Dimension, Options",
      importQuestionsSuccess: "Successfully imported {count} questions",
      typeLikert: "Likert Scale",
      typeForcedChoice: "Forced Choice",
      typeScenario: "Scenario",
      more: "More",
      // Career stages
      stageEntry: "Entry Level",
      stageMid: "Mid-Career",
      stageSenior: "Senior/Entrepreneur",
      stageHR: "HR/OD Professional",
      // Analytics page
      analyticsTitle: "Analytics",
      analyticsDesc: "Assessment data statistics and trend analysis",
      exportReport: "Export Report",
      today: "Today",
      thisWeek: "This Week",
      thisMonth: "This Month",
      thisQuarter: "This Quarter",
      thisYear: "This Year",
      assessmentTrend: "Assessment Trend",
      dailyStats: "Daily assessment statistics",
      startedAssessment: "Started",
      completedAssessment: "Completed",
      anchorTrendChange: "Anchor Trend Changes",
      comparedToPrevious: "Compared to previous period",
      careerStageDistribution: "Career Stage Distribution",
      userComposition: "User composition",
      totalAssessments: "Total Assessments",
      completionRate: "Completion Rate",
      monday: "Mon",
      tuesday: "Tue",
      wednesday: "Wed",
      thursday: "Thu",
      friday: "Fri",
      saturday: "Sat",
      sunday: "Sun",
      // Settings page
      settingsTitle: "System Settings",
      settingsDesc: "Configure system parameters and global options",
      saveSettings: "Save Settings",
      settingsSaved: "Settings saved",
      generalSettings: "General Settings",
      generalSettingsDesc: "System name and basic configuration",
      systemName: "System Name",
      minQuestions: "Minimum Questions",
      maxQuestions: "Maximum Questions",
      sessionSettings: "Session Settings",
      sessionSettingsDesc: "Assessment session and timeout configuration",
      sessionTimeout: "Session Timeout (minutes)",
      sessionTimeoutDesc: "Progress will be auto-saved after this idle time",
      notificationSettings: "Notification Settings",
      notificationSettingsDesc: "Email and system notification configuration",
      emailNotifications: "Email Notifications",
      emailNotificationsDesc: "Send result email after assessment completion",
      weeklyReport: "Weekly Report",
      weeklyReportDesc: "Send weekly system data summary report",
      maintenanceMode: "Maintenance Mode",
      maintenanceModeDesc: "System maintenance and emergency operations",
      enableMaintenance: "Enable Maintenance Mode",
      enableMaintenanceDesc: "Users cannot access assessment system when enabled",
      databaseInfo: "Database Info",
      databaseInfoDesc: "Storage and data status",
      userRecords: "User Records",
      assessmentRecords: "Assessment Records",
      totalQuestionsCount: "Total Questions",
    },
    profile: {
      title: "Profile",
      assessmentHistory: "Assessment History",
      noHistory: "No assessment records",
      startFirst: "Start your first assessment",
    },
    history: {
      title: "Assessment History",
      empty: "No assessment records yet",
      emptyDesc: "After completing an assessment, your results will be saved here",
      testAccountNote: "Test Account History",
      testAccountDesc: "Test account data is for demo only and won't be saved to cloud",
    },
  },
};
